//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC5.UserRegisterFormApps.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class registeredUser
    {
        public System.Guid ID { get; set; }
        public string name { get; set; }
        public string lastName { get; set; }
        public string emailAddress { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<bool> isActive { get; set; }
        public string activationCode { get; set; }
    }
}
